#!/bin/sh

FIRSTTAG=$(git describe --tags --dirty='-*' 2>/dev/null)
RELTAG=$(git describe --tags --long --dirty='-*' --match '[0-9]*.*' 2>/dev/null)

git --no-pager log -1 --date=short \
	--pretty=format:"\usepackage[%
		shash={%h},
		lhash={%H},
		authname={%an},
		authemail={%ae},
		authsdate={%ad},
		authidate={%ai},
		authudate={%at},
		commname={%an},
		commemail={%ae},
		commsdate={%ad},
		commidate={%ai},
		commudate={%at},
		refnames={%d},
		firsttagdescribe={$FIRSTTAG},
		reltag={$RELTAG}
	]{gitexinfo}" HEAD > .git/gitHeadInfo.gin
